hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("overshoot",      { type = "bezier", points = { {0.05, 0.9},  {0.1, 1.1}   } })

hl.animation({ leaf = "global",                enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",                enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",               enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",             enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",            enabled = true, speed = 0.49, bezier = "easeOutQuint", style = "popin 90%" })
hl.animation({ leaf = "windowsMove",           enabled = true, speed = 3,    bezier = "easeOutQuint", style = "slide" })
hl.animation({ leaf = "fadeIn",                enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",               enabled = true, speed = 0.46, bezier = "easeOutQuint" })
hl.animation({ leaf = "fade",                  enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",                enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",              enabled = true, speed = 3,    bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "layersOut",             enabled = true, speed = 1.5,  bezier = "easeOutQuint" })
hl.animation({ leaf = "fadeLayersIn",          enabled = true, speed = 1.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "fadeLayersOut",         enabled = true, speed = 1.39, bezier = "overshoot" })
hl.animation({ leaf = "workspaces",            enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",          enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut",         enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "specialWorkspaceIn",    enabled = true, speed = 2.5,  bezier = "easeInOutCubic", style = "slide top" })
hl.animation({ leaf = "specialWorkspaceOut",   enabled = true, speed = 2.5,  bezier = "overshoot",     style = "slidefade bottom" })
